import { Song, Photo, CountdownItem, SecretMessage, JourneySettings } from '../types/database';
import { FALLBACK_AUDIO } from './romantic-audio';

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song-bgm-1',
    title: 'Sampai Jadi Debu (Acoustic Ambient)',
    artist: 'Banda Neira',
    category: 'bgm',
    audio_url: FALLBACK_AUDIO.bgm,
    cover_url: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=400&auto=format&fit=crop&q=80',
    lyrics: 'Meredup bijak, saling menjaga. Selamanya berdua sampai kita jadi debu...',
    duration: '3:45',
    order_index: 0,
  },
  {
    id: 'song-abadi-1',
    title: 'Lagu Abadi Kita (Sempurna)',
    artist: 'Andra and The Backbone',
    category: 'abadi',
    audio_url: FALLBACK_AUDIO.abadi,
    cover_url: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=400&auto=format&fit=crop&q=80',
    lyrics: 'Kau adalah darahku, kau adalah jantungku. Kau adalah hidupku, lengkapi diriku...',
    duration: '4:20',
    order_index: 1,
  },
  {
    id: 'song-ciyan-1',
    title: 'Monokrom',
    artist: 'Tulus (Pilihan Favorit Ciyan)',
    category: 'ciyan',
    audio_url: FALLBACK_AUDIO.ciyan,
    cover_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    lyrics: 'Di mana pun kalian berada, ku kirimkan terima kasih untuk warna dalam hidupku...',
    duration: '3:34',
    order_index: 2,
  },
  {
    id: 'song-ciyan-2',
    title: 'Until I Found You',
    artist: 'Stephen Sanchez (Pilihan Favorit Ciyan)',
    category: 'ciyan',
    audio_url: FALLBACK_AUDIO.ciyan,
    cover_url: 'https://images.unsplash.com/photo-1494774157365-9e04c6720e47?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    lyrics: 'I would never fall in love until I found her, until I found you...',
    duration: '2:58',
    order_index: 3,
  },
  {
    id: 'song-ciyan-3',
    title: 'Golden Hour',
    artist: 'JVKE (Acoustic Scrapbook Mix)',
    category: 'ciyan',
    audio_url: FALLBACK_AUDIO.ciyan,
    cover_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
    lyrics: 'She got glitter for skin, my radiant beam in the night...',
    duration: '3:29',
    order_index: 4,
  },
  {
    id: 'song-daffa-1',
    title: 'Komang',
    artist: 'Raim Laode (Pilihan Favorit Daffa)',
    category: 'daffa',
    audio_url: FALLBACK_AUDIO.daffa,
    cover_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    lyrics: 'Sebab kau terlalu indah dari sekadar kata. Dunia hentikanlah sejenak...',
    duration: '3:42',
    order_index: 5,
  },
  {
    id: 'song-daffa-2',
    title: "Can't Take My Eyes Off You",
    artist: 'Frankie Valli (Pilihan Favorit Daffa)',
    category: 'daffa',
    audio_url: FALLBACK_AUDIO.daffa,
    cover_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    lyrics: 'You are just too good to be true, cant take my eyes off of you...',
    duration: '3:20',
    order_index: 6,
  },
  {
    id: 'song-daffa-3',
    title: 'Nanti Kita Seperti Ini',
    artist: 'Batas Senja (Pilihan Favorit Daffa)',
    category: 'daffa',
    audio_url: FALLBACK_AUDIO.daffa,
    cover_url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    vinyl_photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    lyrics: 'Ingin punya rumah tuk tempat pulang bersama dirimu setiap senja...',
    duration: '3:50',
    order_index: 7,
  },
];

export const INITIAL_PHOTOS: Photo[] = [
  {
    id: 'photo-1',
    title: 'Awal Mula Chat Pertama',
    caption: 'Masih canggung menyapa lewat pesan singkat larut malam. Siapa sangka ini awal dari segalanya.',
    date: '14 Agustus 2023',
    location: 'Ruang Pesan Kita',
    image_url: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&auto=format&fit=crop&q=80',
    category: 'pdkt',
    rotation: -2,
    order_index: 1,
  },
  {
    id: 'photo-2',
    title: 'Kopi & Hujan Pertama',
    caption: 'Gerimis sore di sudut kedai favorit. Ciyan tersenyum malu saat memesan matcha latte hangat.',
    date: '28 Agustus 2023',
    location: 'Kedai Kopi Sudut Kota',
    image_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
    category: 'pdkt',
    rotation: 3,
    order_index: 2,
  },
  {
    id: 'photo-3',
    title: 'Jalan Sore & Es Krim Gelato',
    caption: 'Berbagi tawa sambil mencicipi rasa gelato favorit kita berdua. Detik itu waktu rasanya berhenti.',
    date: '10 September 2023',
    location: 'Pedestrian Boulevard',
    image_url: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800&auto=format&fit=crop&q=80',
    category: 'pdkt',
    rotation: -1.5,
    order_index: 3,
  },
  {
    id: 'photo-4',
    title: 'Senja di Atas Bukit',
    caption: 'Langit jingga merah muda menemanimu yang bercerita tentang mimpi-mimpimu. Daffa jatuh cinta lagi.',
    date: '20 September 2023',
    location: 'Bukit Bintang Kenangan',
    image_url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80',
    category: 'pdkt',
    rotation: 2.5,
    order_index: 4,
  },
  {
    id: 'photo-5',
    title: 'Hari Resmi Bersama: 29 September',
    caption: 'Di bawah sorot lampu redup dan detak jantung yang berdebar kencang, dua hati berikrar satu tujuan selamanya.',
    date: '29 September 2025',
    location: 'Tempat Rahasia Kita',
    image_url: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&auto=format&fit=crop&q=80',
    category: 'pdkt',
    rotation: -3,
    order_index: 5,
  },
  {
    id: 'photo-6',
    title: 'Kebun Mawar Merah Jambu',
    caption: 'Bunga-bunga vintage bermekaran mengiringi langkah kita bergandengan tangan.',
    date: '18 Oktober 2023',
    location: 'Kebun Raya Asri',
    image_url: 'https://images.unsplash.com/photo-1494774157365-9e04c6720e47?w=800&auto=format&fit=crop&q=80',
    category: '3d_exhibition',
    rotation: 1,
    order_index: 6,
  },
  {
    id: 'photo-7',
    title: 'Malam Cahaya Lilin',
    caption: 'Setiap tatapan matamu memancarkan kehangatan yang menenangkan seluruh gundahku.',
    date: '24 Desember 2023',
    location: 'Bistro Klasik',
    image_url: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800&auto=format&fit=crop&q=80',
    category: '3d_exhibition',
    rotation: -2,
    order_index: 7,
  },
  {
    id: 'photo-8',
    title: 'Menyambut Tahun Baru Berdua',
    caption: 'Harapan pertama di detik pertama tahun baru: agar Ciyan & Daffa selalu bersama selamanya.',
    date: '31 Desember 2023',
    location: 'Dermaga Bintang',
    image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    category: '3d_exhibition',
    rotation: 2,
    order_index: 8,
  },
  {
    id: 'photo-9',
    title: 'Piknik Bunga & Buku Puisi',
    caption: 'Membaca bait-bait romantis sambil menikmati angin sepoi-sepoi di bawah pohon rindang.',
    date: '14 Februari 2024',
    location: 'Taman Sakura Vintage',
    image_url: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&auto=format&fit=crop&q=80',
    category: '3d_exhibition',
    rotation: -1,
    order_index: 9,
  },
  {
    id: 'photo-10',
    title: 'Genggaman Tangan di Pantai',
    caption: 'Deburan ombak senja menjadi saksi genggaman tangan yang takkan pernah saling melepaskan.',
    date: '28 Mei 2024',
    location: 'Pantai Pasir Putih',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    category: '3d_exhibition',
    rotation: 1.5,
    order_index: 10,
  },
  {
    id: 'photo-11',
    title: 'Senyum Manis Ciyan di Hari Bahagia',
    caption: 'Melihat senyum lepasmu adalah kebahagiaan terbesar yang selalu ingin Daffa jaga selamanya.',
    date: '18 April 2024',
    location: 'Paviliun Mawar Merah Muda',
    image_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
    category: '3d_exhibition',
    rotation: -2,
    order_index: 11,
  },
];

export const INITIAL_COUNTDOWNS: CountdownItem[] = [
  {
    id: 'cd-anniv',
    title: 'Hari Jadi Kita (Next Anniversary)',
    target_date: '2027-09-29T00:00:00',
    category: 'anniversary',
    description: 'Momen sakral saat Ciyan & Daffa mengawali kisah cinta abadi pada 29 September.',
    badge: 'Momen Paling Spesial',
  },
  {
    id: 'cd-ciyan',
    title: 'Ulang Tahun Ciyan Terkasih',
    target_date: '2027-04-18T00:00:00',
    category: 'birthday_ciyan',
    description: 'Hari terlahirnya bidadari yang menjadi rumah terhangat bagi Daffa.',
    badge: 'Ciyan Birthday',
  },
  {
    id: 'cd-daffa',
    title: 'Ulang Tahun Daffa Tercinta',
    target_date: '2027-07-12T00:00:00',
    category: 'birthday_daffa',
    description: 'Hari spesial untuk pria yang berjanji menjaga Ciyan seumur hidupnya.',
    badge: 'Daffa Birthday',
  },
  {
    id: 'cd-val',
    title: 'Hari Kasih Sayang (Valentine)',
    target_date: '2027-02-14T00:00:00',
    category: 'valentine',
    description: 'Perayaan cinta dengan setangkai mawar vintage dan secarik surat penuh ketulusan.',
    badge: 'Hari Kasih Sayang',
  },
];

export const INITIAL_SECRET_MESSAGES: SecretMessage[] = [
  {
    id: 'secret-1',
    title: 'Surat Tersembunyi #1: Dari Daffa untuk Ciyan',
    message: 'Untuk Ciyan, gadisku tercantik: Terima kasih sudah memilihku di antara jutaan manusia di bumi ini. Tawamu adalah melodi paling meneduhkan hatiku, dan senyummu adalah matahari di setiap pagiku. Aku berjanji akan setia merawat cinta kita sampai rambut kita memutih bersama.',
    author: 'Daffa',
    scratch_percent_required: 40,
  },
  {
    id: 'secret-2',
    title: 'Surat Tersembunyi #2: Janji 29 September',
    message: 'Angka 29 bukan sekadar tanggal di kalender. Tanggal itu adalah gerbang keajaiban saat semesta menyatukan dua jiwa yang saling melengkapi. Ciyan, apa pun yang terjadi esok hari, tanganmu tidak akan pernah kulepaskan.',
    author: 'Daffa',
    scratch_percent_required: 40,
  },
  {
    id: 'secret-3',
    title: 'Surat Tersembunyi #3: Harapan Cinta Abadi',
    message: 'Semoga setiap lembar scrapbook perjalanan kita selalu dipenuhi kenangan manis, pelukan hangat di kala dingin, dan pengertian yang tiada habisnya. Eternal Love Ciyan & Daffa selamanya!',
    author: 'Both',
    scratch_percent_required: 40,
  },
];

export const INITIAL_JOURNEY_SETTINGS: JourneySettings = {
  startDate: '2025-09-29T00:00:00',
  badgeText: 'Bersama Sejak 29 September 2025',
  title: 'Perjalanan Indah Kita Berdua',
  description: 'Tidak ada satu detik pun yang berlalu tanpa rasa syukur karena memilikimu di sisiku.',
};
